.TH "src/csc5021/solutions/SolutionAbstracts.java" 3 "Sun Dec 22 2013" "Version 1.0" "CSC5021" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/csc5021/solutions/SolutionAbstracts.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcsc5021\&.solutions\&.SolutionAbstracts\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcsc5021\&.solutions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CSC5021 from the source code\&.
